<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN" Id="{66d4f454-7bbd-49ec-95c5-88132eb8edd7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	sanityCheck : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[sanityCheck:=sanityCheck+1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>