name: Check TwinCAT Version

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate-tc-version:
    runs-on: windows-latest

    steps:
      - name: Checkout this repo (with .tsproj)
        uses: actions/checkout@v4

      - name: Clone ActaNonVerba repo into ./actaRepo
        run: git clone https://github.com/porcemon/ActaNonVerba.git ./actaRepo

      - name: Find .tsproj file in this repo
        id: find_tsproj
        shell: pwsh
        run: |
          $proj = Get-ChildItem -Recurse -Filter *.tsproj | Select-Object -First 1
          if (-not $proj) {
            Write-Error "No .tsproj file found."
            exit 1
          }
          echo "projectPath=$($proj.FullName)" >> $env:GITHUB_ENV

      - name: Run version check using script from ActaNonVerba
        shell: pwsh
        run: |
          $scriptPath = ".\actaRepo\.github\workflows\findXmlTagWithAttribute.ps1"
          if (-not (Test-Path $scriptPath)) {
            Write-Error "::error::Script not found at $scriptPath"
            exit 1
          }

          Write-Host "Using script at $scriptPath"

          $result = & $scriptPath `
            -File "$env:projectPath" `
            -Tag "TcSmProject" `
            -Attribute "TcVersion" `
            -Value "3.1.4024.65"

          if ($LASTEXITCODE -ne 0 -or -not $result) {
            Write-Error "::error::Required TcVersion not found in project."
            exit 1
          } else {
            Write-Host "✅ Required TcVersion is present."
          }
