name: Check TwinCAT Version

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate-tc-version:
    runs-on: windows-latest

    steps:
      - name: Checkout TwinCAT project repo
        uses: actions/checkout@v4

      - name: Clone ActaNonVerba repo to get validation script
        run: git clone https://github.com/porcemon/ActaNonVerba.git acta

      - name: Find .tsproj file
        id: find_tsproj
        shell: pwsh
        run: |
          $proj = Get-ChildItem -Recurse -Filter *.tsproj | Select-Object -First 1
          if (-not $proj) {
            Write-Error "No .tsproj file found."
            exit 1
          }
          echo "projectPath=$($proj.FullName)" >> $env:GITHUB_ENV

      - name: Run version check using script from ActaNonVerba
        shell: pwsh
        run: |
          $scriptPath = Resolve-Path "./acta/.github/workflows/findXmlTagWithAttribute.ps1"
          Write-Host "Using script at $scriptPath"
          
          $result = & $scriptPath `
            -File "$env:projectPath" `
            -Tag "TcSmProject" `
            -Attribute "TcVersion" `
            -Value "3.1.4024.65"

          if ($LASTEXITCODE -ne 0 -or -not $result) {
            Write-Error "::error::Required TcVersion not found in project."
            exit 1
          } else {
            Write-Host "✅ Required TcVersion is present."
          }
