name: Check TwinCAT Version (Prepare)

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: windows-latest

    outputs:
      projectPath: ${{ steps.find_tsproj.outputs.projectPath }}

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Download script
        run: |
          Invoke-WebRequest `
            -Uri "https://raw.githubusercontent.com/porcemon/ActaNonVerba/refs/heads/main/.github/workflows/findXmlModuleWithAttribute.ps1" `
            -OutFile "findXmlModuleWithAttribute.ps1"

      - name: Upload script
        uses: actions/upload-artifact@v4
        with:
          name: check-script
          path: findXmlModuleWithAttribute.ps1

      - name: Find .tsproj file
        id: find_tsproj
        shell: pwsh
        run: |
          $proj = Get-ChildItem -Recurse -Filter *.tsproj | Select-Object -First 1
          echo "::set-output name=projectPath::$($proj.FullName)"

  call-validate:
    uses: ./.github/workflows/validate.yml
    needs: prepare
    with:
      projectPath: ${{ needs.prepare.outputs.projectPath }}
