name: Check TwinCAT Version (Download Script)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-version:
    runs-on: windows-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Download script from ActaNonVerba
        shell: pwsh
        run: |
          Invoke-WebRequest `
            -Uri "https://raw.githubusercontent.com/porcemon/ActaNonVerba/refs/heads/main/.github/workflows/findXmlModuleWithAttribute.ps1" `
            -OutFile "findXmlTagWithAttribute.ps1"

      - name: Find .tsproj file
        id: find_tsproj
        shell: pwsh
        run: |
          $proj = Get-ChildItem -Recurse -Filter *.tsproj | Select-Object -First 1
          if (-not $proj) {
            Write-Error "No .tsproj file found."
            exit 1
          }
          echo "projectPath=$($proj.FullName)" >> $env:GITHUB_ENV

      - name: Run downloaded script
        shell: pwsh
        run: |
          & ./findXmlTagWithAttribute.ps1 `
            -File "$env:projectPath" `
            -Tag "TcSmProject" `
            -Attribute "TcVersion" `
            -Value "3.1.4024.65"
